{% set name = 'stsci.numdisplay' %}
{% set version = '1.6.1' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Package for displaying numpy arrays in DS9

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - numpy
    - stsci.tools
    - setuptools
    - python
    run:
    - numpy
    - stsci.tools
    - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.numdisplay
