{% set name = 'stsci.sphere' %}
{% set version = '0.2' %}
{% set number = '2' %}

about:
    home: http://www.stsci.edu/institute/software_hardware
    license: BSD

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - matplotlib
    - numpy
    - setuptools
    - stsci.distutils
    - python
    run:
    - astropy >=1.1
    - matplotlib
    - numpy
    - python

source:
    git_url: https://bitbucket.org/stsci_ssb/{{ name }}.git

test:
    imports:
    - stsci.sphere
