{% set name = 'drizzlepac' %}
{% set version = '2.2.0c' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: AstroDrizzle for HST images

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - d2to1
      - stsci.distutils
      - astropy >=1.1
      - fitsblender
      - graphviz
      - nictools
      - numpydoc
      - numpy {{ numpy }}
      - scipy
      - stsci.convolve
      - stsci.distutils
      - stsci.image
      - stsci.imagemanip
      - stsci.imagestats
      - stsci.ndimage
      - stsci.skypac
      - spherical-geometry
      - sphinx
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - stsci.stimage
      - stsci.tools
      - stwcs
      - pyregion
      - python {{ python }}
      - setuptools
    run:
      - astropy >=1.1
      - fitsblender
      - nictools
      - numpy
      - scipy
      - stsci.convolve
      - stsci.image
      - stsci.imagemanip
      - stsci.imagestats
      - stsci.ndimage
      - stsci.skypac
      - spherical-geometry
      - stsci.stimage
      - stsci.tools
      - stwcs
      - pyregion
      - setuptools
      - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
      - drizzlepac
