{% set name = 'd2to1' %}
{% set version = '0.2.12' %}
{% set number = '0' %}

about:
    home: https://github.com/embray/{{ name }}
    license: BSD
    summary: |
        Allows using distutils2-like setup.cfg files for package metadata
        with a distribute/setuptools setup.py

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python
    run:
    - setuptools
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/embray/{{ name }}.git
