{% set name = 'stsci-data-analysis' %}
{% set version = '2.0.2' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci-data-analysis meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.3
    - astroimtools >=0.1
    - stginga >=0.1
    - specviz >=0.2.3
    #- mosviz
    - photutils >=0.2.2
    - glueviz >=0.9.0
    - imexam >=0.6.2
    - asdf >=1.0.2
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.3
    - astroimtools >=0.1
    - stginga >=0.1
    - specviz >=0.2.3
    #- mosviz
    - photutils >=0.2.2
    - glueviz >=0.9.0
    - imexam >=0.6.2
    - asdf >=1.0.2
    - numpy
    - python
