{% set name = 'stsci' %}
{% set version = '3.0.0' %}
{% set number = '0' %}

about:
    home: http://ssb.stsci.edu
    license: BSD
    summary: stsci meta-package

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - stsci-hst >=3.0.0
    - stsci-data-analysis >=2.0.2
    - astropy >=1.3
    - cfitsio >=3.370
    - d2to1 >=0.2.12
    - ds9 >=7.1
    - fftw >=3.3.4
    - htc_utils >=0.1
    - purge_path >=1.0.0
    - pyds9 >=1.8.1
    - pyfftw >=0.9.2
    - numpy
    - python
    run:
    - stsci-hst >=3.0.0
    - stsci-data-analysis >=2.0.2
    - astropy >=1.3
    - cfitsio >=3.370
    - d2to1 >=0.2.12
    - ds9 >=7.1
    - fftw >=3.3.4
    - htc_utils >=0.1
    - purge_path >=1.0.0
    - pyds9 >=1.8.1
    - pyfftw >=0.9.2
    - numpy
    - python
