{% set name = 'stsci.skypac' %}
{% set version = '0.9.9b' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: stsci.skypac

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - spherical-geometry
    - stsci.distutils
    - stsci.imagestats
    - stsci.tools
    - stwcs
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - astropy >=1.1
    - spherical-geometry
    - stsci.imagestats
    - stsci.tools
    - stwcs
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.skypac
