{% set name = 'gcc' %}
{% set version = '7.2.0' %}
{% set number = '0' %}
{% set filename = 'gcc' + '-' + version + '.tar.gz' %}

about:
    home: http://gcc.gnu.org
    license: GPL
    summary: GNU Compiler Collection

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - mpc
    - mpfr
    - gmp
    - isl
    - cloog
    - zlib

source:
    fn: {{ filename }}
    url: http://ftpmirror.gnu.org/gcc/{{ name }}-{{ version }}/{{ filename }}
    md5: 2e4be17c604ea555e0dff4a8f81ffe44

test:
    commands:
    - gcc --version
    - gcc -v
    - g++ --version
    - g++ -v
    - gfortran --version
    - gfortran -v
    - gccgo --version
    - gccgo -v
