{% set name = 'gcc' %}
{% set version = '7.2.0' %}
{% set number = '0' %}
{% set filename = 'gcc' + '-' + version + '.tar.gz' %}

about:
    home: http://gcc.gnu.org
    license: GPL
    summary: GNU Compiler Collection

build:
    detect_binary_files_with_prefix: true # [not linux32]
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
      - mpc >=1.0.3
      - mpfr >=3.1.5
      - gmp >=6.1.0
      - isl >=0.15
      - cloog 0.18.1
      - zlib >=1.2.11

    run:
      - mpc >=1.0.3
      - mpfr >=3.1.5
      - gmp >=6.1.0
      - isl >=0.15
      - cloog 0.18.1
      - zlib >=1.2.11

source:
    fn: {{ filename }}
    url: http://ftpmirror.gnu.org/gcc/{{ name }}-{{ version }}/{{ filename }}
    md5: 2e4be17c604ea555e0dff4a8f81ffe44

test:
    commands:
    - gcc --version
    - gcc -v
