{% set name = 'pytools' %}
{% set version = '2016.1' %}
{% set number = '2' %}

about:
    home: https://pypi.python.org/{{ name }}
    license: MIT
    summary: A collection of tools for Python

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - decorator >=3.2.0
    - appdirs >=1.4.0
    - six >=1.8.0
    - setuptools
    - numpy
    - python
    run:
    - decorator >=3.2.0
    - appdirs >=1.4.0
    - six >=1.8.0
    - numpy
    - python

source:
    fn: {{ name }}-{{ version }}.tar.gz
    md5: d8af5c5bea24aa4a21881684dcf03b06
    url:
    - https://pypi.python.org/packages/source/p/{{ name }}/{{ name }}-{{ version }}.tar.gz

test:
    imports:
    - pytools
