{% set name = 'stsci.image' %}
{% set version = '2.3.0' %}
{% set number = '2' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        Image array manipulation functions

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - cio-bt [win]
    - numpy {{ numpy }}
    - scipy
    - stsci.distutils
    - stsci.tools
    - setuptools
    - python {{ python }}
    run:
    - astropy >=1.1
    - numpy
    - scipy
    - stsci.tools
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.image
