{% set name = 'drizzle' %}
{% set version = '1.5' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: A package for combining dithered images into a single image

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

requirements:
    build:
    - astropy >=1.1
    - setuptools
    - numpy
    - python x.x

    run:
    - astropy >=1.1
    - numpy
    - python x.x

test:
    imports:
    - drizzle
    - drizzle.drizzle
    - drizzle.cdrizzle

