{% set name = 'asdf-standard' %}
{% set version = '1.0.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: Standards reference for ASDF

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - sphinx
    - jsonschema
    - pyyaml
    - mistune
    - six [py27|py3k]
    - setuptools
    - python
    run:
    - nose
    - astropy >=1.1
    - setuptools
    - python

source:
    git_tag: {{ tag }}
    git_url: https://github.com/spacetelescope/{{ name }}.git
