{% set name = 'sphinx_rtd_theme' %}
{% set version = '0.1.9' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: https://pypi.python.org/packages/source/s/{{ name }}
    license: BSD
    summary: |
        ReadTheDocs.org theme for Sphinx, 2013 version

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - sphinx
    - setuptools
    - python {{ python }}
    run:
    - sphinx
    - python

source:
    fn: {{ name }}-{{ version }}.tar.gz
    md5: 86a25c8d47147c872e42dc84cc66f97b
    url: https://pypi.python.org/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz

test:
    imports:
    - sphinx_rtd_theme
