{% set name = 'stsci.convolve' %}
{% set version = '2.2.1' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: "Image array convolution functions"

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - cio-bt [win]
    - d2to1
    - stsci.distutils
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.convolve
