{% set name = 'aprio' %}
{% set version = '1.0.1' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

about:
    home: http://bitbucket.org/jhunkeler/{{ name }}
    license: GPL
    summary: aprio is an automatic renice daemon.

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - python
    - setuptools
    - psutil
    - python-daemon
    - docutils
    run:
    - psutil
    - python-daemon
    - docutils
    - python

source:
    git_tag: {{ tag }}
    git_url: https://bitbucket.org/jhunkeler/{{ name }}.git
