{% set name = 'stsci.distutils' %}
{% set version = '0.3.8' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: |
        distutils/packaging-related utilities used by older STScI packages

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - setuptools
    - numpy {{ numpy }}
    - python {{ python }}
    run:
    - nose
    - numpy
    - python

source:
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - stsci.distutils
