{% set name = 'verhawk' %}
{% set version = '0.0.2' %}
{% set number = '0' %}

about:
    home: http://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: A simple Python package version scanner

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - setuptools
    - python
    run:
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - verhawk
