{% set name = 'wfc3tools' %}
{% set version = '1.3.4' %}
{% set number = '1' %}

about:
    home: https://github.com/spacetelescope/{{ name }}
    license: BSD
    summary: For analyzing and calibrating HST-WFC3 data

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - numpy {{ numpy }}
    - setuptools
    - python {{ python }}
    - matplotlib
    - scipy
    - stsci.tools
    run:
    - astropy >=1.1
    - numpy
    - python
    - stsci.tools
    - matplotlib
    - scipy

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}.git

test:
    imports:
    - wfc3tools
