{% set name = 'stsci.tools' %}
{% set version = '3.4.11' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/stsci.tools
    license: BSD
    summary: |
        Collection of tools specific to STScI packages

build:
    number: {{ number }}
    preserve_egg_dir: 'yes'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - d2to1
    - astropy >=1.1
    - pytools
    - setuptools
    - stsci.distutils
    - numpy
    - python {{ python }}
    run:
    - astropy >=1.1
    - numpy
    - pytools
    - stsci.distutils
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ name }}

test:
    imports:
    - stsci.tools
