{% set name = 'llvm-lldb' %}
{% set version = '3.9.0' %}
{% set number = '0' %}

about:
    home: http://llvm.org
    license: BSD
    summary: LLVM debugger package

package:
    name: {{ name }}
    version: {{ version }}

build:
    number: {{ number }}

source:
    fn: {{ name }}-{{ version }}.src.tar.gz
    url: http://llvm.org/releases/{{version}}/lldb-{{version}}.src.tar.xz

requirements:
    build:
    - cmake
    - llvm {{version}}
    - llvm-clang {{version}}
    - setuptools
    - python x.x

    run:
    - llvm {{version}}
    - llvm-clang {{version}}

#test:
#   imports:
#   # - (e.g. a_python_module)
#
#   commands:
#   # - (e.g. program --help)
