{% set name = 'spherical-geometry' %}
{% set reponame = 'spherical_geometry' %}
{% set version = '1.0.12' %}
{% set number = '0' %}

about:
    home: https://github.com/spacetelescope/{{ reponame }}
    license: BSD
    summary: For handling spherical polygons that represent arbitrary regions of the sky

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - astropy >=1.1
    - matplotlib
    - setuptools
    - numpy
    - python {{ python }}
    run:
    - astropy >=1.1
    - matplotlib
    - numpy
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/spacetelescope/{{ reponame }}.git

test:
    imports:
    - spherical_geometry
