{% set name = 'pyobjc-framework-quartz' %}
{% set version = '3.1.1' %}
{% set number = '0' %}

about:
    home: http://pyobjc.sourceforge.net/
    license: MIT
    summary: Wrappers for the Quartz frameworks on Mac OS X

build:
    skip: True [not osx]
    number: {{ number }}
    preserve_egg_dir: 'true'

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - pyobjc-core =={{ version }}
    - pyobjc-framework-cocoa =={{ version }}
    - setuptools
    - python
    run:
    - pyobjc-core =={{ version }}
    - pyobjc-framework-cocoa =={{ version }}
    - python

source:
    fn: pyobjc-{{ version }}.tar.gz
    url: https://bitbucket.org/ronaldoussoren/pyobjc/get/pyobjc-{{ version }}.tar.bz2

#test:
    # - see runtest.py
