{% set name = 'purge_path' %}
{% set version = '1.2.0' %}
{% if version[0] == 'v' %}
{%   set version = version[1:] %}
{% endif %}
{% set number = '1' %}

about:
    home: https://github.com/jhunkeler/{{ name }}
    license: BSD
    summary: purge_path a small PATH manipulator

build:
    number: {{ number }}

package:
    name: {{ name }}
    version: {{ version }}

requirements:
    build:
    - python {{ python }}
    - setuptools
    run:
    - python

source:
    git_tag: {{ version }}
    git_url: https://github.com/jhunkeler/{{ name }}.git
